AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Glue Workflow stack"
Parameters:
  AWSGlueRole:
    Type: String
    Default: "arn:aws:iam::471112749040:role/AwsGlueRole"
    Description: IAM role for AWS GLue.
  ENV:
    Type: String
    Default: dev
    AllowedPattern: ^(dev|test|prod|[a-z][0-9]+)$
    Description: Enter dev, test, prod or Syngenta user id. Default is dev.
  S3Env:
    Type: String
    Default: DEV
    AllowedPattern: ^(DEV|TEST|PROD|DEV\/users\/[a-z][0-9]+)$
    Description: Enter DEV, TEST, or PROD or relative path to user folder for example DEV/users/s123456. Default is DEV.
  BucketName:
    Type: String
    MinLength: "1"
    Default: mycicdartifactsbucket
    AllowedValues:
      - mycicdartifactsbucket
    Description:  Ingestion Bucket 
  MioName:
    Type: String
    MinLength: "1"
    Description:  Mio name
  MioNumber:
    Type: String
    MinLength: "1"
    Description:  Mio Number
  WorkflowName:
    Type: String
    MinLength: "1"
    Description:  Workflow name
  ExtractionGlueJobName:
    Type: String
    MinLength: "1"
  LoadGlueJobName:
    Type: String
    MinLength: "1"
  RefdataExtractionGlueJobName:
    Type: String
    MinLength: "1"  
  ConnectionType:
    Type: String
    MinLength: "3"
    Description:  Connection type
  Owner:
    Type: String
    MinLength: 1
    Description: Owner of the mio
#  Method:
#    Type: String
#    MinLength: "3"
#    Description: Table extraction Method
  RegionName:
    Type: String
    MinLength: "1"
    Default: ap-south-1
    AllowedValues:
      - ap-south-1
    Description:  AWS Region
  SecretName:
    Type: String
    MinLength: "1"
    Description: AWS Secret Credentails
  TopicARN:
    Type: String
    MinLength: "1"
    Description: AWS Topic ARN Name
  AccountNumberAWS:
    Type: Number
    Default: 471112749040
Conditions:   
  CreateScheduleTrigger: !Equals [ !Ref S3Env, PROD ]
Resources:
  LoadGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: 3
        ScriptLocation: !Sub "s3://${BucketName}/${S3Env}/scripts_glue/mio225_legal_invoices/${WorkflowName}/glue_jobs/${MioName}_${WorkflowName}_${LoadGlueJobName}.py"
      GlueVersion: 4.0
      Connections:
        Connections:
          - !Ref ConnectionType
      # NumberOfWorkers: 10
      # WorkerType: "G.1X"
      DefaultArguments:
        "--extra-py-files": !Sub "s3://${BucketName}/${S3Env}/python_lib/redshift_module-0.1-py3.6.egg,s3://${BucketName}/${S3Env}/python_lib/python_lib-0.1-py3-none-any.whl"
        "--env": !Ref ENV         
        "--region_name": !Ref RegionName
        "--load_type": "delta" 
        "--topic_arn": !Ref TopicARN
        "--job-bookmark-option": "job-bookmark-disable"
        "--TempDir": !Sub "s3://${BucketName}/${S3Env}/legal_invoices/glue_temporary/"
      Name: !Sub "${MioName}_${WorkflowName}_${LoadGlueJobName}_${ENV}"
      Role: !Ref AWSGlueRole
      Tags:
        mio: !Ref MioNumber
        env: !Ref ENV
        owner: !Ref Owner
  RefdataLoadGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: 3
        ScriptLocation: !Sub "s3://${BucketName}/${S3Env}/scripts_glue/mio225_legal_invoices/${WorkflowName}/glue_jobs/${MioName}_${WorkflowName}_${RefdataExtractionGlueJobName}.py"
      GlueVersion: 1.0
      Connections:
        Connections:
          - !Ref ConnectionType
      # NumberOfWorkers: 10
      # WorkerType: "G.1X"
      DefaultArguments:
        "--extra-py-files": !Sub "s3://${BucketName}/${S3Env}/python_lib/redshift_module-0.1-py3.6.egg,s3://${BucketName}/${S3Env}/python_lib/python_lib-0.1-py3-none-any.whl,s3://${BucketName}/${S3Env}/python_lib/s3fs-0.4.2-py3-none-any.whl,s3://${BucketName}/${S3Env}/python_lib/pyarrow-0.17.0-cp36-cp36m-manylinux1_x86_64.whl"               
        "--region_name": !Ref RegionName
        "--s3_src_bucket": "synddfile"
        "--s3_tgt_bucket": "synintegration" 
        "--s3_env": !Ref ENV        
        "--topic_arn": !Ref TopicARN
        "--job-bookmark-option": "job-bookmark-disable"
        "--TempDir": !Sub "s3://${BucketName}/${S3Env}/legal_invoices/glue_temporary/"
      Name: !Sub "${MioName}_${WorkflowName}_${RefdataExtractionGlueJobName}_${ENV}"
      Role: !Ref AWSGlueRole
      Tags:
        mio: !Ref MioNumber
        env: !Ref ENV
        owner: !Ref Owner

 
